/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.dgproducoes.martinello.salgado.views;

import br.com.dgproducoes.martinello.salgado.control.ClienteControl;
import br.com.dgproducoes.martinello.salgado.model.Cliente;
import com.towel.swing.table.ObjectTableModel;
import java.util.LinkedList;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author david
 */
public class TelaConsultaFuncionario extends javax.swing.JInternalFrame {

    private final ObjectTableModel<Cliente> otmCliente = new ObjectTableModel<>(Cliente.class, "nome,email,cpf,dataNascimento,situacao");
    private ClienteControl clienteControl;

    /**
     * Creates new form TelaConsultaPagamentos
     */
    public TelaConsultaFuncionario() {
        initComponents();

        clienteControl = new ClienteControl();
        btImprimir.setEnabled(false);
        btVisualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pConsulta = new javax.swing.JPanel();
        rCpf = new javax.swing.JLabel();
        jftfCpf = new javax.swing.JFormattedTextField();
        rNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();
        rCpf1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpConsultaCliente = new javax.swing.JTable();
        jpsStatus = new javax.swing.JPanel();
        rJpsStatus = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Consulta Funcionário");

        pConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        rCpf.setText("CPF:");

        try {
            jftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        rNome.setText("Nome:");

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        btPesquisar.setMnemonic('p');
        btPesquisar.setText("Pesquisar");
        btPesquisar.setToolTipText("");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btImprimir.setMnemonic('i');
        btImprimir.setText("Imprimir");

        btVisualizar.setMnemonic('v');
        btVisualizar.setText("Visualizar");

        javax.swing.GroupLayout pConsultaLayout = new javax.swing.GroupLayout(pConsulta);
        pConsulta.setLayout(pConsultaLayout);
        pConsultaLayout.setHorizontalGroup(
            pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pConsultaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(rCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsultaLayout.createSequentialGroup()
                        .addComponent(rNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rCpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pConsultaLayout.setVerticalGroup(
            pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rCpf)
                    .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rCpf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(btImprimir)
                    .addComponent(btVisualizar))
                .addContainerGap())
        );

        tpConsultaCliente.setModel(otmCliente);
        jScrollPane1.setViewportView(tpConsultaCliente);

        jpsStatus.setPreferredSize(new java.awt.Dimension(14, 35));

        javax.swing.GroupLayout jpsStatusLayout = new javax.swing.GroupLayout(jpsStatus);
        jpsStatus.setLayout(jpsStatusLayout);
        jpsStatusLayout.setHorizontalGroup(
            jpsStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rJpsStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsStatusLayout.setVerticalGroup(
            jpsStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsStatusLayout.createSequentialGroup()
                .addComponent(rJpsStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
            .addComponent(jpsStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        if (jtfNome.getText().length() > 1 || jftfCpf.getText().replaceAll(" ", "").length() > 3) {
            pesquisar();
        } else {

            pesquisarSemWhere();

        }


    }//GEN-LAST:event_btPesquisarActionPerformed

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jftfCpf;
    private javax.swing.JPanel jpsStatus;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JPanel pConsulta;
    private javax.swing.JLabel rCpf;
    private javax.swing.JLabel rCpf1;
    private javax.swing.JLabel rJpsStatus;
    private javax.swing.JLabel rNome;
    private javax.swing.JTable tpConsultaCliente;
    // End of variables declaration//GEN-END:variables

    public void pesquisar() {
        Cliente cliente = new Cliente();

        final TelaProcesso telaProcessamento = new TelaProcesso("Realizando consulta...");

        new Thread() {
            @Override
            public void run() {
                try {
                    cliente.setCpf(jftfCpf.getText());
                    cliente.setNome(jtfNome.getText());

                    List<Cliente> lCliente = clienteControl.pesquisaFireBase(cliente);
                    if (lCliente.size() > 0) {
                        carregaTabela(lCliente);
                        rJpsStatus.setText("Pesquisa realizada com sucesso!!!");

                    } else {
                        rJpsStatus.setText("Erro ao pesquisar cliente: Cliente não encontrado");
                    }

                    for (Cliente cliente1 : lCliente) {
                        rCpf1.setText(cliente1.getCpf());

                    }

                } finally {
                    SwingUtilities.invokeLater(() -> {
                        telaProcessamento.dispose();
                    });
                }

            }
        }.start();

        telaProcessamento.setVisible(true);
        telaProcessamento.requestFocusInWindow();

    }

    public void pesquisarSemWhere() {

        final TelaProcesso telaProcessamento = new TelaProcesso("Realizando consulta...");

        new Thread() {
            @Override
            public void run() {
                try {
                    List<Cliente> lCliente = clienteControl.read();
                    carregaTabela(lCliente);
                    rCpf1.setText("");
                } finally {
                    SwingUtilities.invokeLater(() -> {
                        telaProcessamento.dispose();
                    });
                }

            }
        }.start();

        telaProcessamento.setVisible(true);
        telaProcessamento.requestFocusInWindow();

        rJpsStatus.setText("Pesquisa realizada com sucesso!!!");

    }

    public void carregaTabela(List<Cliente> lCliente) {

        otmCliente.setData(lCliente);
        otmCliente.fireTableDataChanged();
        tpConsultaCliente.grabFocus();
        limparCampos();
    }

    public static String formataDados(String dado) {
        dado = dado.replaceAll("StringProperty", "");
//        dado = dado.replace('[', '');
        return dado;
    }

    public void limparCampos() {
        jftfCpf.setText("");
        jtfNome.setText("");
    }

}
